# Ga naar de publieke map
cd /root/public_site

# Genereer een uitgebreide SOTA Portfolio
cat << 'EOF_SITE' > index.html
<!DOCTYPE html>
<html lang='nl' class='dark'>
<head>
    <script src='https://cdn.tailwindcss.com'></script>
    <title>MRTNHT | AI ARCHITECT</title>
</head>
<body class='bg-slate-950 text-slate-300 font-sans'>
    <div class='max-w-4xl mx-auto px-6 py-24'>
        <div class='mb-20'>
            <h1 class='text-7xl font-black text-white mb-2 bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent'>MRTNHT</h1>
            <p class='text-xl font-mono text-cyan-500/80 tracking-tighter'>SYSTEM ARCHITECT & AI OPERATOR</p>
        </div>

        <div class='space-y-12'>
            <section class='p-10 bg-white/5 border border-white/10 rounded-[2rem] backdrop-blur-xl'>
                <h2 class='text-2xl font-bold text-white mb-4'>🚀 De Phoenix Factory</h2>
                <p class='text-slate-400 leading-relaxed mb-6'>
                    Een volledig autonoom ecosysteem draaiend op Android hardware. 
                    Mijn systeem maakt gebruik van SSH-tunnels, GitHub API-bridges en real-time listeners om code te genereren en te deployen zonder menselijke tussenkomst.
                </p>
                <div class='flex gap-3'>
                    <span class='px-4 py-1 bg-cyan-500/10 text-cyan-400 rounded-full text-xs border border-cyan-500/20'>Ubuntu 22.04</span>
                    <span class='px-4 py-1 bg-blue-500/10 text-blue-400 rounded-full text-xs border border-blue-500/20'>Termux Engine</span>
                </div>
            </section>
        </div>

        <footer class='mt-20 pt-10 border-t border-white/5 text-sm font-mono text-slate-600'>
            GENERATED BY PHOENIX COMMAND CENTER V50 | STATUS: ONLINE
        </footer>
    </div>
</body>
</html>
EOF_SITE

# Push de update naar de wereld
eval $(ssh-agent -s)
ssh-add /root/.ssh/id_rsa
git add .
git commit -m "Live Content Update via Remote Bridge"
git push origin main
